#!/bin/bash

filename=$(basename $1)
extension=${filename##*.}
filename=${filename%.*}

# Convert Rnw to md
echo Attempting to convert $1 to $filename'.md ...'
expr='library("ascii");Pandoc("'$1'")'
R --slave -e $expr

# Convert md to pdf
mdfilename=$filename'.md'
echo Attempting to convert $mdfilename to $filename'.pdf ...'
markdown2pdf $mdfilename
